included: # paths to include during linting. `--path` is ignored if present.
- AssessmentRound1TechBase

disabled_rules:
- trailing_whitespace

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`
  - private_outlet
  - private_action

function_body_length:
  - 100
  - 100

function_parameter_count:
  - 10
  - 10

line_length:
  warning: 200
  error: 200
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: 2 # only min_length

