# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'AssessmentRound1TechBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Remote pod
	pod 'HNImageView', '0.3.3'
  pod 'SwiftLint'

  # Local pod
  pod 'TBVNetWork', :path => '../SubModules/TBVNetWork'
  pod 'TBVExtensions', :path => '../SubModules/TBVExtensions'
  pod 'TBVCommon', :path => '../SubModules/TBVCommon'

  target 'AssessmentRound1TechBaseTests' do
    inherit! :search_paths
  end

  target 'AssessmentRound1TechBaseUITests' do
  end

end
